using System.Collections.Generic;

using System.Diagnostics;

using Terraria.ID;



namespace EvenMoreOverpoweredJourney.FurnitureBlueprint

{

    /// <summary>分帧识别：每帧仅消耗有限时间，避免单帧卡死。</summary>

    public sealed class FurnitureRecognitionJob

    {

        public enum Phase

        {

            Done = 0,

            Preparing = 1,

            Classifying = 2,

            Finalizing = 3

        }



        public int SeedType { get; }

        public int AnchorBlock { get; }

        public FurnitureScheme Scheme { get; internal set; }

        public Phase CurrentPhase { get; internal set; } = Phase.Classifying;

        public bool IsComplete => CurrentPhase == Phase.Done;



        internal List<int> CandidateList { get; }

        internal int ClassifyIndex { get; set; }

        internal Dictionary<FurnitureSlotKind, List<int>> PerSlot { get; }

        internal FurnitureRecognizeContext Ctx { get; }

        internal FurnitureStyleSignature BlockSig { get; private set; }

        internal FurnitureCraftStationProfile Stations { get; private set; }

        internal int MaterialBlock { get; private set; }

        internal int RejectedPlaceable { get; set; }

        internal int RejectedClassify { get; set; }

        internal int RejectedBlockBucket { get; set; }



        internal int FinalizeStep { get; set; }

        internal int FinalizeWikiSlotIndex { get; set; }

        internal int FinalizePlaceholderSlotIndex { get; set; }

        internal HashSet<int> FinalizeCandidates { get; set; }

        internal HashSet<int> FinalizeExpanded { get; set; }

        internal bool FinalizeExpandedBuilt { get; set; }

        internal HashSet<int> FinalizeOccupied { get; set; }

        internal bool FinalizeLoggedSlots { get; set; }

        internal int PrepareStep { get; set; }

        internal FurnitureScheme PrepareScheme { get; set; }

        internal FurnitureStyleSignature PrepareSignature { get; set; }

        internal FurnitureCraftStationProfile PrepareStations { get; set; }

        internal FurnitureStyleSignature PrepareBlockSig { get; set; }

        internal int PrepareResolvedAnchor { get; set; }

        internal int PrepareMaterialBlock { get; set; }

        internal HashSet<int> PrepareCandidates { get; set; }

        internal bool PrepareLoggedBegin { get; set; }

        internal int PrepareCollectPhase { get; set; }

        internal FurnitureSetConfidenceReport PrepareConfidence { get; set; }

        internal FurnitureRecognitionJob(

            int seedType,

            int anchorBlock,

            FurnitureScheme scheme,

            List<int> candidates,

            int materialBlock,

            FurnitureStyleSignature blockSig,

            FurnitureCraftStationProfile stations)

        {

            SeedType = seedType;

            AnchorBlock = anchorBlock;

            Scheme = scheme;

            CandidateList = candidates;

            MaterialBlock = materialBlock;

            BlockSig = blockSig;

            Stations = stations;

            Ctx = new FurnitureRecognizeContext();

            PerSlot = new Dictionary<FurnitureSlotKind, List<int>>();

            foreach (FurnitureSlotKind wikiSlot in FurnitureWikiSlots.RecognitionOrder)

                PerSlot[wikiSlot] = new List<int>();

        }



        public static FurnitureRecognitionJob CreatePending(int seedType, int anchorBlock)
        {
            var job = new FurnitureRecognitionJob(
                seedType,
                anchorBlock,
                new FurnitureScheme { SeedType = seedType, IsAutoGenerated = true },
                new List<int>(),
                ItemID.None,
                default,
                default);
            job.CurrentPhase = Phase.Preparing;
            return job;
        }

        internal void ImportPrepared(FurnitureRecognitionJob prepared)
        {
            if (prepared == null)
                return;

            Scheme = prepared.Scheme;
            CandidateList.Clear();
            CandidateList.AddRange(prepared.CandidateList);
            MaterialBlock = prepared.MaterialBlock;
            BlockSig = prepared.BlockSig;
            Stations = prepared.Stations;
            CurrentPhase = Phase.Classifying;
            ClassifyIndex = 0;
        }

        public static FurnitureRecognitionJob CreateCompleted(FurnitureScheme scheme, int seed, int anchor)
        {
            var job = new FurnitureRecognitionJob(
                seed,
                anchor,
                scheme,
                new List<int>(),
                scheme.AnchorMaterialType,
                default,
                default);
            job.CurrentPhase = Phase.Done;
            job.Scheme = scheme;
            return job;
        }

    }



    public static class FurnitureRecognitionRunner

    {

        public const int FrameBudgetMs = 14;

        public const int MinClassifyBatch = 6;

        public const int MaxClassifyBatch = 18;



        public static bool Tick(FurnitureRecognitionJob job, int budgetMs = FrameBudgetMs)

        {

            if (job == null || job.IsComplete)

                return true;



            var sw = Stopwatch.StartNew();

            if (job.CurrentPhase == FurnitureRecognitionJob.Phase.Preparing)
            {
                try
                {
                    if (!job.PrepareLoggedBegin)
                    {
                        job.PrepareLoggedBegin = true;
                        FurnitureBlueprintLog.InfoFull(
                            $"recognize prepare begin seed={job.SeedType} block={job.AnchorBlock}");
                    }

                    while (sw.ElapsedMilliseconds < budgetMs)
                    {
                        int remainingMs = budgetMs - (int)sw.ElapsedMilliseconds;
                        if (remainingMs < 1)
                            break;

                        if (FurnitureSetRecognizer.TickPrepareRecognitionJob(job, remainingMs, out FurnitureRecognitionJob prepared))
                        {
                            if (prepared != null)
                                job.ImportPrepared(prepared);
                            else
                                job.CurrentPhase = FurnitureRecognitionJob.Phase.Done;
                            break;
                        }
                    }
                }
                catch (System.Exception ex)
                {
                    FurnitureBlueprintDiagnostics.LogRecognizeFailure(job.SeedType, job.AnchorBlock, ex, "prepare");
                    job.CurrentPhase = FurnitureRecognitionJob.Phase.Done;
                    return true;
                }

                return job.IsComplete;
            }

            if (job.CurrentPhase == FurnitureRecognitionJob.Phase.Classifying)

            {

                int batch = 0;

                while (sw.ElapsedMilliseconds < budgetMs

                       && job.ClassifyIndex < job.CandidateList.Count

                       && batch < MaxClassifyBatch)

                {

                    int type = job.CandidateList[job.ClassifyIndex++];

                    FurnitureSetRecognizer.ClassifyOneCandidate(type, job);

                    batch++;

                }



                if (batch < MinClassifyBatch && job.ClassifyIndex < job.CandidateList.Count)

                {

                    while (job.ClassifyIndex < job.CandidateList.Count && batch < MinClassifyBatch)

                    {

                        int type = job.CandidateList[job.ClassifyIndex++];

                        FurnitureSetRecognizer.ClassifyOneCandidate(type, job);

                        batch++;

                    }

                }



                if (job.ClassifyIndex >= job.CandidateList.Count)
                {
                    job.CurrentPhase = FurnitureRecognitionJob.Phase.Finalizing;
                    job.FinalizeStep = 0;
                }

                return false;
            }

            if (job.CurrentPhase == FurnitureRecognitionJob.Phase.Finalizing)

            {

                int remainingMs = budgetMs - (int)sw.ElapsedMilliseconds;

                if (remainingMs < 1)

                    remainingMs = 1;



                try

                {

                    if (FurnitureSetRecognizer.TickFinalizeScheme(job, remainingMs))

                        job.CurrentPhase = FurnitureRecognitionJob.Phase.Done;

                }

                catch (System.Exception ex)

                {

                    FurnitureBlueprintDiagnostics.LogRecognizeFailure(job.SeedType, job.AnchorBlock, ex, "finalize");

                    FurnitureBlueprintLog.Warn(

                        $"recognize finalize aborted seed={job.SeedType} block={job.AnchorBlock}: {ex.GetType().Name}");

                    job.CurrentPhase = FurnitureRecognitionJob.Phase.Done;

                }



                return job.IsComplete;

            }



            return false;

        }

    }

}


