using System;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader.IO;

namespace EvenMoreOverpoweredJourney.FurnitureBlueprint
{
    /// <summary>一套 22 类槽位的家具方案（维基 20 件 + 方块 + 墙）。</summary>
    public sealed class FurnitureScheme
    {
        public string DisplayName { get; set; } = "";
        public int SeedType { get; set; }
        public int AnchorMaterialType { get; set; }
        /// <summary>套组封面物品（默认材料块；列表/卡片展示用）。</summary>
        public int IconItemType { get; set; }
        public bool IsAutoGenerated { get; set; } = true;
        public long CreatedUtcTicks { get; set; } = DateTime.UtcNow.Ticks;

        public int[] SlotItemTypes { get; } = new int[FurnitureSlotKinds.Count];

        public FurnitureScheme Clone()
        {
            var c = new FurnitureScheme
            {
                DisplayName = DisplayName,
                SeedType = SeedType,
                AnchorMaterialType = AnchorMaterialType,
                IconItemType = IconItemType,
                IsAutoGenerated = IsAutoGenerated,
                CreatedUtcTicks = CreatedUtcTicks
            };
            Array.Copy(SlotItemTypes, c.SlotItemTypes, FurnitureSlotKinds.Count);
            return c;
        }

        public void ClearSlots()
        {
            for (int i = 0; i < FurnitureSlotKinds.Count; i++)
                SlotItemTypes[i] = ItemID.None;
        }

        public void SetSlot(FurnitureSlotKind kind, int itemType)
        {
            int idx = FurnitureSlotKinds.ToIndex(kind);
            if (idx >= 0)
                SlotItemTypes[idx] = itemType;
        }

        public int GetSlot(FurnitureSlotKind kind)
        {
            int idx = FurnitureSlotKinds.ToIndex(kind);
            return idx >= 0 ? SlotItemTypes[idx] : ItemID.None;
        }

        public int ResolveCoverItemType()
        {
            if (IconItemType > ItemID.None)
                return IconItemType;

            for (int i = 0; i < SlotItemTypes.Length; i++)
            {
                if (SlotItemTypes[i] > ItemID.None)
                    return SlotItemTypes[i];
            }

            return AnchorMaterialType > ItemID.None ? AnchorMaterialType : ItemID.None;
        }

        public TagCompound ToTag(string id)
        {
            var tag = new TagCompound
            {
                ["id"] = id,
                ["name"] = DisplayName ?? "",
                ["seed"] = SeedType,
                ["anchor"] = AnchorMaterialType,
                ["icon"] = IconItemType,
                ["auto"] = IsAutoGenerated,
                ["utc"] = CreatedUtcTicks
            };
            for (int i = 0; i < FurnitureSlotKinds.Count; i++)
                tag[$"s{i}"] = SlotItemTypes[i];
            return tag;
        }

        public static FurnitureScheme FromTag(TagCompound tag)
        {
            var s = new FurnitureScheme
            {
                DisplayName = tag.GetString("name") ?? "",
                SeedType = tag.GetInt("seed"),
                AnchorMaterialType = tag.GetInt("anchor"),
                IconItemType = tag.ContainsKey("icon") ? tag.GetInt("icon") : ItemID.None,
                IsAutoGenerated = tag.GetBool("auto"),
                CreatedUtcTicks = tag.GetLong("utc")
            };
            for (int i = 0; i < FurnitureSlotKinds.Count; i++)
                s.SlotItemTypes[i] = tag.ContainsKey($"s{i}") ? tag.GetInt($"s{i}") : ItemID.None;
            return s;
        }
    }
}
